version: '3'
services:
    api-nginx:
        build:
            context: ./docker
            dockerfile: nginx.docker
        volumes:
            - ./:/var/www
        ports:
            - "8000:80"
        networks:
            - laravel

    api-php-fpm:
        build:
            context: ./docker
            dockerfile: php-fpm.docker
        volumes:
            - ./:/var/www
        depends_on:
            - db
        networks:
            - laravel

    api-php-cli:
        build:
            context: ./docker
            dockerfile: php-cli.docker
        volumes:
            - ./:/var/www
        depends_on:
            - db
        working_dir: /var/www
        tty: true
        networks:
            - laravel

    db:
        image: adambh/mariadb-alpine
        volumes:
            - ./storage/docker/mysql:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_USER=app"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_DATABASE=app"
        ports:
            - "33066:3306"
        networks:
            - laravel

    redis:
        image: redis:6-alpine
        ports:
            - "63791:6379"
        networks:
            - laravel

    cron:
        build:
            context: ./docker
            dockerfile: cron.dockerfile
        tty: true
        volumes:
            - ./:/var/www
        networks:
            - laravel

    rabbitmq:
        image: rabbitmq:3-management
        environment:
            RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
            RABBITMQ_DEFAULT_USER: rabbit
            RABBITMQ_DEFAULT_PASS: rabbit
        ports:
            - "8085:15672"
            - "5672:5672"
        volumes:
            - ./docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
        networks:
            - laravel

networks:
    laravel:
